/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ILender, ILenderInterface } from "../ILender";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "collateralETHDeposited",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amountUSDMinted",
        type: "uint256",
      },
    ],
    name: "Deposit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "collateralETHWithdraw",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amountUSDBurned",
        type: "uint256",
      },
    ],
    name: "Withdraw",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amountToDeposit",
        type: "uint256",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "repaymentAmount",
        type: "uint256",
      },
    ],
    name: "estimateCollateralAmount",
    outputs: [
      {
        internalType: "uint256",
        name: "collateralAmount",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "depositAmount",
        type: "uint256",
      },
    ],
    name: "estimateTokenAmount",
    outputs: [
      {
        internalType: "uint256",
        name: "tokenAmount",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "userAddress",
        type: "address",
      },
    ],
    name: "getLender",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "collateralETH",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "debtAmount",
            type: "uint256",
          },
        ],
        internalType: "struct ILender.LenderEntity",
        name: "lender",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "repaymentAmount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ILender__factory {
  static readonly abi = _abi;
  static createInterface(): ILenderInterface {
    return new utils.Interface(_abi) as ILenderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILender {
    return new Contract(address, _abi, signerOrProvider) as ILender;
  }
}
